/*
STUDENT NO. : 	2016-90653
STUDENT NAME:	Karen Michelle A. Alarcon
-----------------------------------------------------------------------------------------------------------------------------------
REFERENCES:
- Horton, Ivor. Beginning C From Novice to Professional. New York: Apress, 2006. Book.
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define N 15
#define MAX_SIZE 200

//the Input data structure
typedef struct Input{
	char Data[10];
}Input;

//the BST data structure
typedef struct BST{
	int n;
	struct Input* key[N];
	double p[N];
	double q[N];
	double c[N][N];
	int root[N][N];	
}BST;

//function to create Data
Input *createData(char data[]){
	Input *newData = malloc(sizeof(Input));
	memcpy(newData->Data, data, sizeof(newData->Data));
	return newData;
}

//function to add new data to the key field
void addData(BST *B, char data[], int i){
	Input *newData = createData(data);
	B->key[i] = newData;
}

//function to get the data input from the first line
void GET_DATA_1(char buf[], BST *B){
	char *ptr = strtok(buf, " ");
	char data[N];
	int i = 1;

	while( ptr != NULL)
	{
		strcpy(data,ptr);
		addData(B,data,i);
		i++;
		ptr = strtok(NULL, " ");
	}
	B->n = i-1;
}

//function to get the data input from the second line
void GET_DATA_2(char buf[], BST *B){
	char *ptr = strtok(buf, " ");
	int i = 1;

	while( ptr != NULL){
		B->p[i] = atof(ptr);
		i++;
		ptr = strtok(NULL, " ");
	}
}

//function to get the data input from the third line
void GET_DATA_3(char buf[], BST *B){
	char *ptr = strtok(buf, " ");
	int i = 0;

	while( ptr != NULL){
		B->q[i] = atof(ptr);
		i++;
		ptr = strtok(NULL, " ");
	}
}

//function to compute for the OPTIMUM BST
void OPTIMUM_BST(BST *B){
	int i, j, r, s, x = 9999;
	double w[N][N], cost;
	
	for (i=0; i<=B->n; i++){
		B->c[i][i] = 0;
		w[i][i] = B->q[i];
	}
	
	for(s=1; s<=B->n; s++){
		for(i=0; i<=B->n-s; i++){
			j = i + s;
			w[i][j] = w[i][j-1] + B->p[j] + B->q[j];
			B->c[i][j] = x;
			for(r=i+1; r<=j; r++){
				cost = w[i][j] + B->c[i][r-1] + B->c[r][j];
				if(cost < B->c[i][j]){
					B->c[i][j] = cost;
					B->root[i][j] = r;
				}
			}
		}
	}
	
}

//function to display the result of OPTIMUM BST
void DISPLAY_BST(BST B, int i, int j){
	if (i==j){
		printf("NULL, ");
		return;
	}else{
		printf("%s, ", B.key[B.root[i][j]]->Data);
		DISPLAY_BST(B,i,B.root[i][j]-1);
		DISPLAY_BST(B,B.root[i][j],j);
	}
}

int main() {
	
	//initialization of variables
	BST B;
	char inputfile[MAX_SIZE];
	char buf[MAX_SIZE];

	printf("Program Started.\n\n");			//program start prompt
	printf("Enter file name> ");			//ask user to type in the file to read
	scanf("%s", inputfile);					//save the file name to inputfile variable

	FILE *file = fopen(inputfile,"r");		//open and read the file

	fgets(buf, sizeof(buf), file);			//get the string from the current line
	GET_DATA_1(buf, &B);					//function call to get the data from the input
	
	fgets(buf, sizeof(buf), file);			//get the string from the current line
	GET_DATA_2(buf, &B);					//function call to get the data from the input

	fgets(buf, sizeof(buf), file);			//get the string from the current line
	GET_DATA_3(buf, &B);					//function call to get the data from the input
	
	OPTIMUM_BST(&B);						//function call to compute the OPTIMAL_BST
	printf("Optimal BST: ");				//output prompt

	DISPLAY_BST(B, 0, B.n);					//function call to display the result generated by the OPTIMUM_BST procedure
	
	printf("\n\nProgram Terminated.\n");	//program termination prompt
	
	fclose(file);							//close the file

}
